# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}
  goos:
  - darwin
  - linux
  # windows fails with an error https://github.com/kovetskiy/mark/runs/5034726426?check_suite_focus=true
  # - windows
  goarch:
  - amd64
  - arm64
archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Publish on Homebrew Tap
brews:
  -
    name: mark
    repository:
      owner: kovetskiy
      name: homebrew-mark
      branch: master

    commit_author:
      name: Egor Kovetskiy
      email: e.kovetskiy@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    directory: Formula

    homepage: "https://github.com/kovetskiy/mark"
    description: "Sync your markdown files with Confluence pages."
    license: "Apache 2.0"

    test: |
      system "#{bin}/program", "version"
